const fs = require('fs');
const content = fs.readFileSync('src/Bloque3_Resumen.jsx', 'utf8');
const lines = content.split('\n');

let startExportIdx = -1;
let endExportIdx = -1;

for (let i = 0; i < lines.length; i++) {
  if (lines[i].includes('const exportarAExcelAuditable = async () => {')) {
    startExportIdx = i;
  }
  if (lines[i].trim() === 'return (' && startExportIdx !== -1) {
    endExportIdx = i;
    break;
  }
}

if (startExportIdx !== -1 && endExportIdx !== -1) {
  const part1 = lines.slice(0, startExportIdx).join('\n');
  const part3 = lines.slice(endExportIdx).join('\n');
  
  const skeleton = [
    '  // ─── EXPORTACIÓN EXCEL CON EXCELJS (REESTRUCTURACIÓN TRIBUTARIA) ────────',
    '  const exportarAExcelAuditable = async () => {',
    '    const ExcelJS = (await import(''exceljs'')).default;',
    '    const { saveAs } = await import(''file-saver'');',
    '',
    '    const wb = new ExcelJS.Workbook();',
    '    wb.creator = ''Beigel SRL'';',
    '    wb.created = new Date();',
    '',
    '    const TC = tipoCambio || 7500;',
    '    const esDolar = monedaTrabajo === ''USD'';',
    '    ',
    '    const cvtP = (usdVal) => esDolar ? usdVal : usdVal * TC;',
    '    const cvtS = (gsVal) => esDolar ? gsVal / TC : gsVal;',
    '    const round = (val) => esDolar ? Math.round(val * 100) / 100 : Math.round(val);',
    '    ',
    '    const numStyle = { numFmt: esDolar ? ''#,##0.00'' : ''#,##0'' };',
    '    const pctStyle = { numFmt: ''0.00%'' };',
    '',
    '    // ─── 1. PROCESAMIENTO Y PRORRATEO OCULTO ───',
    '    let CD_Global = 0;',
    '    let granTotalOriginal = 0;',
    '    const allItems = [];',
    '',
    '    detalleProcura.forEach(eq => {',
    '      const qty = eq.cantidad || 1;',
    '      const fobT = (eq.costoBase || 0) * qty;',
    '      const fleteT = eq.tipoFlete === ''porcentaje'' ? fobT * ((eq.valorFlete||0)/100) : (eq.valorFlete||0)*qty;',
    '      const segT = (fobT + fleteT) * ((eq.porcentajeSeguro||0)/100);',
    '      const cifT = fobT + fleteT + segT;',
    '      const arT = cifT * ((eq.porcentajeArancel||0)/100);',
    '      const desT = cifT * ((eq.porcentajeDespacho||0)/100);',
    '      const flLocT = eq.aplicarFleteLocal ? ((eq.montoFleteLocal||0)*qty) : 0;',
    '      const finT = cifT * ((eq.porcentajeFinanciero||0)/100);',
    '      const admT = cifT * ((eq.porcentajeAdmin||0)/100);',
    '      const lcT = cifT + arT + desT + flLocT + finT + admT;',
    '      const mg = Math.min(0.99, (eq.margenPorcentaje||0)/100);',
    '      const pvT = mg < 1 ? lcT / (1 - mg) : lcT;',
    '      ',
    '      const cd = round(cvtP(lcT)); // Landed cost es el Costo Directo Base',
    '      const pt_orig = round(cvtP(pvT));',
    '      const margen = pt_orig - cd;',
    '      ',
    '      CD_Global += cd;',
    '      granTotalOriginal += pt_orig;',
    '      allItems.push({ desc: eq.nombre || ''Suministro'', qty, cd, margen, tipo: ''procura'' });',
    '    });',
    '',
    '    detalleServicios.forEach(item => {',
    '      const qty = item.cantidad || 1;',
    '      const cU = round(cvtS(item.costo_directo_unitario || 0));',
    '      const cd = cU * qty;',
    '      const pt_orig = round(cvtS((item.precio_unitario_final || 0) * qty));',
    '      const margen = pt_orig - cd;',
    '      ',
    '      CD_Global += cd;',
    '      granTotalOriginal += pt_orig;',
    '      allItems.push({ desc: item.equipo || ''Servicio'', qty, cd, margen, tipo: ''servicio'' });',
    '    });',
    '',
    '    // Costos Indirectos Globales (Polizas: Fiel 5% + Anticipo 20% + Contingencia 3% = 28%)',
    '    const CI_Total = round(granTotalOriginal * 0.28);',
    '',
    '    let subtotalFinal = 0;',
    '    allItems.forEach(item => {',
    '      item.peso = CD_Global > 0 ? item.cd / CD_Global : 0;',
    '      item.prorrateo = round(item.peso * CI_Total);',
    '      item.pvNeto = item.cd + item.prorrateo + item.margen;',
    '      ',
    '      const pvIvaExacto = item.pvNeto * 1.1;',
    '      item.puIva = round(pvIvaExacto / item.qty);',
    '      item.ptIva = item.puIva * item.qty;',
    '      subtotalFinal += item.ptIva;',
    '    });',
    '',
    '    // ==========================================',
    '    // HOJA 1: PROPUESTA COMERCIAL',
    '    // ==========================================',
    '    const ws1 = wb.addWorksheet(''Propuesta Comercial'');',
    '    ws1.addRow([''PROPUESTA COMERCIAL - PRECIOS CON IVA INCLUIDO'']);',
    '    ws1.addRow([''Moneda de Trabajo:'', monedaTrabajo, ''Tipo de Cambio:'', TC]);',
    '    ws1.addRow([]);',
    '',
    '    ws1.addRow([''Ítem'', ''Producto / Servicio'', ''Cant.'', ''PU (Precio Unitario)'', ''PT (Precio Total)'']);',
    '    ',
    '    allItems.forEach((item, idx) => {',
    '      const r = ws1.addRow([idx + 1, item.desc, item.qty, item.puIva, item.ptIva]);',
    '      r.getCell(4).style = numStyle; r.getCell(5).style = numStyle;',
    '    });',
    '    ',
    '    ws1.addRow([]);',
    '    const iva10 = round(subtotalFinal / 11);',
    '    ws1.addRow(['''', '''', '''', ''Subtotal:'', subtotalFinal]).getCell(5).style = numStyle;',
    '    ws1.addRow(['''', '''', '''', ''IVA 10%:'', iva10]).getCell(5).style = numStyle;',
    '    ws1.addRow(['''', '''', '''', ''Presupuesto Total:'', subtotalFinal]).getCell(5).style = numStyle;',
    '',
    '    // ==========================================',
    '    // HOJA 2: AUDITORIA GERENCIAL',
    '    // ==========================================',
    '    const ws2 = wb.addWorksheet(''Auditoria Gerencial'');',
    '    ws2.addRow([''AUDITORIA GERENCIAL INTERNA (CONFIDENCIAL Y PRORRATEADA)'']);',
    '    ws2.addRow([''Moneda:'', monedaTrabajo, ''TC:'', TC, ''CI Total (Pólizas):'', CI_Total]);',
    '    ws2.addRow([]);',
    '',
    '    ws2.addRow([''Ítem'', ''Producto / Servicio'', ''Cant.'', ''Costo Directo Base'', ''Peso Relativo (%)'', ''Prorrateo Asignado'', ''Margen Bruto'', ''Precio Venta Neto'', ''Precio Venta c/ IVA'']);',
    '    ',
    '    let tCD = 0, tProrrateo = 0, tMargen = 0, tNeto = 0;',
    '    allItems.forEach((item, idx) => {',
    '      tCD += item.cd; tProrrateo += item.prorrateo; tMargen += item.margen; tNeto += item.pvNeto;',
    '      const r = ws2.addRow([',
    '        idx + 1, item.desc, item.qty, ',
    '        item.cd, item.peso, item.prorrateo, item.margen, item.pvNeto, item.puIva',
    '      ]);',
    '      r.getCell(4).style = numStyle;',
    '      r.getCell(5).style = pctStyle;',
    '      r.getCell(6).style = numStyle;',
    '      r.getCell(7).style = numStyle;',
    '      r.getCell(8).style = numStyle;',
    '      r.getCell(9).style = numStyle;',
    '    });',
    '    ',
    '    const rTot = ws2.addRow(['''', ''TOTALES'', '''', tCD, 1, tProrrateo, tMargen, tNeto, '''']);',
    '    rTot.font = { bold: true };',
    '    [4, 6, 7, 8].forEach(c => rTot.getCell(c).style = numStyle);',
    '    rTot.getCell(5).style = pctStyle;',
    '',
    '    // ==========================================',
    '    // HOJA 3: CONDICIONES COMERCIALES',
    '    // ==========================================',
    '    wb.addWorksheet(''Condiciones Comerciales'');',
    '',
    '    const buffer = await wb.xlsx.writeBuffer();',
    '    const blob = new Blob([buffer], { type: ''application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'' });',
    '    const fecha = new Date().toISOString().slice(0, 10).replace(/-/g, '''');',
    '    saveAs(blob, ''Beigel_SRL_Oferta_EPC_'' + fecha + ''.xlsx'');',
    '  };'
  ].join('\n');

  fs.writeFileSync('src/Bloque3_Resumen.jsx', part1 + skeleton + '\n  ' + part3, 'utf8');
  console.log('REESTRUCTURACION APPLIED.');
} else {
  console.log('Indexes not found:', startExportIdx, endExportIdx);
}
